services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: bank
      POSTGRES_PASSWORD: bank
      POSTGRES_DB: bank
    ports:
      - "5432:5432"
    volumes:
      - bank_pg:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bank -d bank"]
      interval: 5s
      timeout: 3s
      retries: 20
    restart: unless-stopped

  smtp4dev:
    image: rnwood/smtp4dev:latest
    ports:
      - "5000:80"    # web UI
      - "2525:25"    # SMTP
    restart: unless-stopped

volumes:
  bank_pg:
